### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by pedrojxsantos** [rt-evil-inc/gira-mais#27]
Olá,

Estou a tentar instalar a app via MacOS 14.7.2, com Xcode e Cocoapods configurados, e encontro este erro:

```
user@MacBook-Pro bin % git clone git@github.com:rt-evil-inc/gira.git
cd gira
Cloning into 'gira'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

```

Alguém sabe o que se pode passar? Tentei fazer o seguinte:

`user@MacBook-Pro bin % git remote add origin https://github.com/rt-evil-inc/gira
error: remote origin already exists.`

Pode ser só noobice. Agradeço mesmo qualquer ajuda.

**Comment by rodrigohpalmeirim** [comment]
Olá!
O problema tem a ver com as chaves de SSH associadas à conta de GitHub. Como as instruções que pusémos usam o URL SSH em vez do URL HTTPS ele devolve um erro por não ter a chave associada à conta. As instruções [aqui](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) dizem como associar. Alternativamente, pode simplesmente ser usado o URL HTTPS:
```sh
git clone https://github.com/rt-evil-inc/gira.git
```
Para que isto não aconteça mais vezes, acho melhor de facto mudarmos a documentação para o URL HTTPS.

**Comment by pedrojxsantos** [comment]
Obrigado, Rodrigo! Consegui avançar até à configuração, mas deparei-me com um novo erro:

`Build description signature: 21868518d0827e367b10e73f643abb98
        Build description path:
        /Users/pedrojoao/gira/ios/DerivedData/00008030-000C455A3E43802E/Build/Intermediates.noindex/XCBuildData/21868518d0827e367b10e73f643abb98.xcbuilddata
        /Users/pedrojoao/gira/ios/App/App.xcodeproj: error: Signing for
        "GiraPlus" requires a development team. Select a development team in the
        Signing & Capabilities editor. (in target 'GiraPlus' from project 'App')
        warning: Run script build phase '[CP] Embed Pods Frameworks' will be run
        during every build because it does not specify any outputs. To address
        this issue, either add output dependencies to the script phase, or
        configure it to run in every build by unchecking "Based on dependency
        analysis" in the script phase. (in target 'GiraPlus' from project 'App')
        ** BUILD FAILED **
        
        
        The following build commands failed:
        Building workspace App with scheme GiraPlus and configuration Debug
        (1 failure)
`

No Xcode fui à secção Signing & Capabilities e dei com o seguinte:

`Failed Registering Bundle Identifier
The app identifier "dev.tteles.gira" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again.
`

Posso fazer alguma coisa para prosseguir? Obrigado mais uma vez.

**Comment by rodrigohpalmeirim** [comment]
Nunca tentei compilar para iOS portanto não sei como é, mas assumo que não seja suposto assinar a app com o nosso identificador.
@joaodcp, podes dar alguma dica, pls?

**Comment by joaodcp** [comment]
Olá @pedrojxsantos

Este segundo problema tem a ver com o bundle identifier que, por já estar a ser utilizado por nós na distribuição da app nas plataformas da Apple, não pode ser usado por outro utilizador.

**Na secção Signing e Capabilities do Xcode, basta trocar o valor do campo "Bundle Identifier" para um identifier único teu e diferente do "dev.tteles.gira".**

De facto é um passo que não está documentado nos build steps, e uma melhoria a adicionar. Obrigado!

**Comment by pedrojxsantos** [comment]
Muito obrigado, @rodrigohpalmeirim e @joaodcp, pelo cuidado e pela paciência – da qual vou pedir mais um pouco 😅

Consegui resolver a questão do Bundle Identifier, mas tenho ainda dois build commands que falham:

` error: Sandbox: bash(4634) deny(1) file-read-data
        /Users/pedrojoao/gira/ios/App/Pods/Target Support
        Files/Pods-GiraPlus/Pods-GiraPlus-frameworks.sh (in target 'GiraPlus'
        from project 'App')
        /bin/sh: /Users/pedrojoao/gira/ios/App/Pods/Target Support
        Files/Pods-GiraPlus/Pods-GiraPlus-frameworks.sh: Operation not permitted
        
        ** BUILD FAILED **
        
        
        The following build commands failed:
        PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks
        /Users/pedrojoao/gira/ios/DerivedData/00008030-000C455A3E43802E/Build/Intermediates.noindex/App.build/Debug-iphoneos/GiraPlus.build/Script-9592DBEFFC6D2A0C8D5DEB22.sh
        (in target 'GiraPlus' from project 'App')
        Building workspace App with scheme GiraPlus and configuration Debug
        (2 failures)
` 

Apareceu um prompt a sugerir que no Xcode, em **Build Phases > [CP] Embed Pods Frameworks > Run script** desse uncheck a "Based on dependency analysis", e assim o fiz, mas parece não ter surtido efeito.

Desculpem continuar a chatear e boa semana!

**Comment by joaodcp** [comment]
Sem problema @pedrojxsantos  :)

Podes ir à tab "Build Settings" no target "GiraPlus"e, com a opção "All" selecionada no switcher Basic/Customized/All, pesquisar por ENABLE_USER_SCRIPT_SANDBOXING?

Na secção "Build Options", qual é o valor do campo "User Script Sandboxing"?

**Comment by pedrojxsantos** [comment]
Obrigado, @joaodcp :) Troquei esse valor para NO, o que me parece ter resolvido aqueles dois build commands, mas agora devolveu-me outro problema:

```
✔ Running xcodebuild in 7.47s
✖ Deploying GiraPlus.app to 00008030-000C455A3E43802E - failed!
[error] TypeError: socket.@write is not a function. (In 'socket.@write(chunk,
        encoding)', 'socket.@write' is undefined)
        at _write (node:net:659:32)
        at writeOrBuffer (internal:streams/writable:283:70)
        at <anonymous> (internal:streams/writable:249:16)
        at write
        (/Users/pedrojoao/gira/node_modules/native-run/dist/ios/lib/protocol/lockdown.js:53:16)
        at <anonymous>
        (/Users/pedrojoao/gira/node_modules/native-run/dist/ios/lib/protocol/protocol.js:107:25)
        at new Promise (native)
        at sendMessage
        (/Users/pedrojoao/gira/node_modules/native-run/dist/ios/lib/protocol/protocol.js:86:20)
        at <anonymous>
        (/Users/pedrojoao/gira/node_modules/native-run/dist/ios/lib/client/lockdownd.js:31:48)
        at startService
        (/Users/pedrojoao/gira/node_modules/native-run/dist/ios/lib/client/lockdownd.js:29:24)
        at <anonymous>
        (/Users/pedrojoao/gira/node_modules/native-run/dist/ios/lib/manager.js:65:84)
```
        
Talvez este seja o final boss 😅 Já estivemos mais longe!

**Comment by joaodcp** [comment]
@pedrojxsantos esse erro já não sei bem do que se trata e não consigo reproduzir.

Estás só a tentar instalar em iOS para usar normalmente?
Se quiseres só usar sem o hassle de fazer build temos a app disponível no TestFlight se preferires que partilhe o URL :)

**Comment by pedrojxsantos** [comment]
isso mesmo, @joaodcp! podes partilhar comigo o URL, por favor?

**Comment by joaodcp** [comment]
Sem problema!

Aqui vai: https://testflight.apple.com/join/e9wdnQ9T

**Comment by pedrojxsantos** [comment]
olá, @joaodcp, espero-te bem. a aplicação tem funcionado lindamente até hoje, recebo um aviso a dizer `"Gira +" Beta caducou`. há forma de ultrapassar isto? obrigado desde já

**Comment by joaodcp** [comment]
Olá @pedrojxsantos!
Desculpa a demora na resposta :) a nossa licença de desenvolvedor da Apple expirou e por isso a aplicação deixou de estar disponível no TestFlight.
A EMEL fez também algumas alterações na maneira como a verificação dos dispositivos é feita através da API deles.

Entretanto já corrigimos tudo e renovámos a licença. Já deves conseguir utilizar outra vez!
